repos:
-   repo: local
    hooks:
    -   id: docker-compiler-check
        name: Docker C++ Problem Solve Check
        entry: sh
        args:
        - -c
        - |
            docker build --tag=cpp-ps-check --file=Dockerfile .
            docker run --rm --mount type=bind,source="$(pwd)",target=/app cpp-ps-check /bin/sh -c "cd $dir && g++ -std=c++11 -pedantic $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"
        language: system
        pass_filenames: false
        verbose: true
        files: \.(cpp)$


